language: php

env:
  - JS_BUILD=false

dist: trusty

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  include:
    - php: 5.5
      env: JS_BUILD=true

before_script:
  - composer install --prefer-source
  - if [[ "$JS_BUILD" == true ]]; then npm install; fi

script:
  - composer test
  - if [[ "$JS_BUILD" == true ]]; then npm test; fi

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
