language: php

env:
  - JS_BUILD=false

dist: trusty

php:
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm

before_script:
  - composer install --prefer-source

script:
  - composer test

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
